"""Goal model and status enumeration for autonomous goal engine (RFC-1006)."""

from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, Field
from uuid_extensions import uuid7str


class GoalStatus(str, Enum):
    """Goal lifecycle states (RFC-1006 Section 5)."""

    PENDING = "pending"
    ACTIVE = "active"
    BLOCKED = "blocked"
    COMPLETED = "completed"
    FAILED = "failed"


class Goal(BaseModel):
    """Autonomous goal model (RFC-1006 Section 5).

    A goal represents an objective the agent should attempt to complete.
    Goals are created by users, events, or self-generated by the agent kernel.
    """

    id: str = Field(default_factory=uuid7str, description="Unique goal identifier (UUID7)")
    description: str = Field(description="Human-readable goal description")
    priority: int = Field(ge=0, le=100, default=50, description="Goal priority (0-100, higher = more important)")
    status: GoalStatus = Field(default=GoalStatus.PENDING, description="Current goal lifecycle status")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(tz=timezone.utc),
        description="Goal creation timestamp",
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(tz=timezone.utc),
        description="Last update timestamp",
    )
    parent_goal_id: str | None = Field(default=None, description="Parent goal ID for hierarchical goals")

    class Config:
        """Pydantic config."""

        use_enum_values = True
        json_encoders = {
            datetime: lambda v: v.isoformat(),
        }
